- hosts: kube_node
  tasks:
    - name: Install nfs-common
      ansible.builtin.apt:
        name: nfs-common
    - name: Configure multipath
      ansible.builtin.template:
        src: templates/multipath.conf
        dest: /etc/multipath.conf
        mode: '0644'
    - name: Restart service multipathd
      ansible.builtin.systemd_service:
        state: restarted
        name: multipathd.service

- hosts: kube_control_plane
  become: false
  tasks:
    - name: Add Longhorn repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
    - name: Install Longhorn
      kubernetes.core.helm:
        name: longhorn
        release_namespace: longhorn-system
        create_namespace: true
        chart_ref: longhorn/longhorn
        chart_version: 1.6.2
        wait: true