---
- hosts: kube_control_plane
  become: false
  tasks:
    - name: Gather nginx controller ip info
      setup:
      delegate_to: "{{item}}"
      delegate_facts: true
      with_items: "{{groups['nginx_controller']}}"
      when: "{{hostvars[item]['ansible_default_ipv4'] is not defined}}"
    
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars
    
    - name: Display all variables/facts known for a host
      debug:
        var: groups

    - name: Install Nginx Chart
      kubernetes.core.helm:
        name: nginx-controller
        release_namespace: nginx-controller
        create_namespace: true
        chart_ref: oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller
        values:
          service:
            externalIPs:
              - "{{ hostvars[groups['nginx_controller'][0]]['ansible_default_ipv4']['address'] }}"
          nodeSelector:
            kubernetes.io/hostname: "{{ groups['nginx_controller'][0] }}"
