- name: Install helm binary on master
  ansible.builtin.import_playbook: app/helm.yml

- name: Install the nginx ingress controller
  ansible.builtin.import_playbook: app/nginx-ingress-controller.yml

- name: Install cert manager
  ansible.builtin.import_playbook: app/cert-manager.yml

- name: Install longhorn storage
  ansible.builtin.import_playbook: app/longhorn.yml
